import java.time.Clock;

public class WashingMachine extends Device {
    private String brand;
    private String model;
    private boolean running;
    // 🔢 ID counter for WM devices
    private static int counter = 1;

    private static String generateId() {
        return "WM" + String.format("%03d", counter++);
    }



    // ✅ Constructor for loading from saved data (id is known)
    public WashingMachine(String id, String name, String brand, String model) {
        super(id, name, "WashingMachine", Clock.systemDefaultZone());
        this.brand = brand;
        this.model = model;
        this.running = false;
    }

    // ✅ Constructor for interactive creation (id will be generated by superclass)
    public WashingMachine(String name, String brand, String model, Clock clock) {
        super(generateId(), name, "WashingMachine", clock);
        this.brand = brand;
        this.model = model;
        this.running = false;
    }


    public void start() {
        if (!isOn()) {
            System.out.println("⚠️ Please turn on the washing machine first.");
            return;
        }
        if (running) {
            System.out.println("🌀 Washing machine is already running.");
        } else {
            running = true;
            System.out.println("🧺 Washing machine started.");
        }
    }

    public void stop() {
        if (running) {
            running = false;
            System.out.println("🛑 Washing machine stopped.");
        } else {
            System.out.println("ℹ️ Washing machine is not running.");
        }
    }

    public String getBrand() {
        return brand;
    }

    public String getModel() {
        return model;
    }

    public boolean isRunning() {
        return running;
    }

    @Override
    public String toString() {
        return "WashingMachine {" +
                "name='" + getName() + '\'' +
                ", id='" + getId() + '\'' +
                ", brand='" + brand + '\'' +
                ", model='" + model + '\'' +
                ", power=" + (isOn() ? "On" : "Off") +
                ", running=" + (running ? "Yes" : "No") +
                '}';
    }

    @Override
    public void simulate() {
        // Optionally simulate cycle steps
    }


    @Override
    public String toDataString() {
        return String.join("|", getType(), getId(), getName(), brand, model);
    }
}
